### ISSUE TITLE
Rooster

### ISSUE THREAD

**Issue by hugojongholt** [maikelmo/rpr-intranet-issues#11]
Hallo Maikel,

Bestaande roosters kan ik niet bewerken.
Oude roosters kan ik wel verwijderen.
Nieuwe roosters kan ik niet aanmaken.

Samen ontdekt met René Wiegman of zo ik weet niet wat zn achternaam precies is.

~ Huo

**Comment by maikelmo** [comment]
Opgelost. Roosteroverzicht werkt weer
