### ISSUE TITLE
Specialisaties Marechaussee

### ISSUE THREAD

**Issue by nietlulu** [maikelmo/rpr-intranet-issues#13]
Hoi Maikel,

Ik zie dat je geen specialisaties kan aanvinken bij leden van de KMar.
Bij de Politie kan dit bijvoorbeeld weer wel.

https://gyazo.com/824804460205da141a29f13d0f8eb982

Groet,
Max L.

**Comment by maikelmo** [comment]
Database fout. Direct opgepakt

**Comment by roleplayreality** [comment]
Worden niet weergegeven in GMS. KMAR kan zich hierdoor niet inmelden
