### ISSUE TITLE
Volgorde academieaanvragen

### ISSUE THREAD

**Issue by roleplayreality** [maikelmo/rpr-intranet-issues#20]
De volgorde van de academievragen is momenteel helemaal door elkaar gehusseld. 

![image](https://user-images.githubusercontent.com/59165205/149426383-48eb7341-c563-4ddd-9aa3-d531a61d98a5.png)

**Comment by maikelmo** [comment]
Academieaanvragen worden gesorteerd op basis van afdeling. Per afdeling worden de aanvragen gesorteerd op basis van binnenkomst. Degene die het langst open staat, staan bovenaan
